name: CI/CD workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Извлечение репозитория
    - name: Checkout
      uses: actions/checkout@v4

    # Установка Python c кэшированим зависимостей для pip
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify Gzip Archive
      run: |
        if ! file datasets/crackstation-human-only-utf8-filtered-sorted.txt.gz | grep gzip > /dev/null; then
          echo "Error: The file is not a valid gzip archive."
          exit 1

    - name: Run tests
      run: |
        cd datasets
        ls
        python test.py