name: Test Python Package
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Pull LFS objects
        run: git lfs pull

      # Установка Python c кэшированим зависимостей для pip
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Configure poetry
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/cache@v3
        name: Enable cache
        with:
          path: ./pwdkek-python/.venv
          key: venv-${{ hashFiles('pwdkek-python/poetry.lock') }}

      - name: Install dependencies
        working-directory: ./pwdkek-python
        run: poetry install

      - name: Run tests (small dataset)
        run: |
          cd pwdkek-python
          export PYTHONPATH=$(pwd):$PYTHONPATH
          python tests/test.py --dataset_path ../datasets/rockyou-utf8-filtered-sorted.txt.gz

      - name: Run tests (big dataset)
        run: |
          cd pwdkek-python
          export PYTHONPATH=$(pwd):$PYTHONPATH
          python tests/test.py --dataset_path ../datasets/crackstation-human-only-utf8-filtered-sorted.txt.gz